DRAFT: Initial support for CA Certificates for endpoints
anynines/stratos pull request #21
Opened 2023-08-24 07:40 UTC by bmo-at-a9s

This PR adapts https://github.com/cloudfoundry/stratos/pull/4824 into a state that may be merged into our repo.
For now, it is in draft stage. It should NOT be merged unless taken out of draft stage.

2023-08-24 07:45 UTC, bmo-at-a9s commented
Before this gets merged, I would like to wait for work on https://github.com/anynines/stratos/tree/feature/INT-2910-GH-Actions-cf-deploy to finish and be merged back into `develop`, so as to be able to rebase this branch on those changes and make sure everything still works.

2023-08-24 07:45 UTC, bmo-at-a9s commented
@mafolz

2023-08-24 12:48 UTC, bmo-at-a9s commented
This can now be reviewed and is no longer a draft, but merging should stay blocked by https://github.com/anynines/stratos/tree/feature/INT-2910-GH-Actions-cf-deploy

2023-09-08 07:05 UTC, mafolz approved these changes

2023-11-08 13:26 UTC, mafolz requested changes

2023-11-17 12:06 UTC, bmo-at-a9s commented on src/frontend/packages/core/src/features/endpoints/create-endpoint/create-endpoint-cf-step-1/create-endpoint-cf-step-1.component.html
> +  <mat-checkbox [disabled]="showCACertField" matInput name="skipSll" formControlName="skipSllField">Skip SSL validation for the endpoint</mat-checkbox>
Done 👌🏻

2023-11-17 12:08 UTC, bmo-at-a9s commented on src/jetstream/http_client.go
> +	rootCAs, _ := x509.SystemCertPool()
Done 👌🏻

2023-11-17 12:12 UTC, bmo-at-a9s commented on src/jetstream/http_client.go
> +	defaulHTTPClientCcnnectionTimeout int64
fixed

2023-11-17 12:40 UTC, mafolz approved these changes

2023-11-17 12:40 UTC, merged